### ISSUE TITLE
Why is the minified size very big (over 700K)

### ISSUE THREAD

**Issue by drnkwati** [kelvinau/circular-audio-wave#1]
Good work
But the minified size is just too much
From you src code i did not expect the file size to be over 7K

**Comment by kelvinau** [comment]
The large size is due to the library ECharts used for rendering. I currently just use the full version of the library, which is 700KB already. We can actually select the necessary features from ECharts and remove the rest. This will reduce the minified size a lot.

Also, I used babel to convert it for IE as I use a lot of ES6 syntax. However, I forgot that IE didn't support Web Audio API...so it's unnecessary to consider IE in here (or I can just add polyfill for that). I will remove babel or simply just uglify it instead.

**Comment by kelvinau** [comment]
Reduced file size of `dist/circular-audio-wave.min.js` by more than half to 321KB. See 3c24092c4e57ffc9965996496f01d81c720b023f and 306f295054a2d11531de4d5557cec76987d161bc.
